# Generated by Django 5.1.3 on 2024-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyeritems_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeritems',
            name='expiration_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
