# Generated by Django 5.1.3 on 2024-11-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grain', 'Grain'), ('dairy-products', 'Dairy Products'), ('mushrooms', 'Mushrooms'), ('herbs-spices', 'Herbs and Spices'), ('grapes', 'Grapes'), ('bee-products', 'Bee Products'), ('other', 'Other')], max_length=50),
        ),
    ]
