# Generated by Django 5.1.3 on 2024-11-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
