# Generated by Django 5.1.3 on 2024-11-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
