# Generated by Django 5.1.3 on 2024-11-26 13:38

import agro_marketplace.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0005_alter_message_options_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name=agro_marketplace.accounts.models.Profile),
        ),
    ]
