# Generated by Django 5.1.3 on 2024-11-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_photo'),
        ('agro_messages', '0006_alter_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='agro_messages.message')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to='accounts.profile')),
            ],
            options={
                'unique_together': {('message', 'profile')},
            },
        ),
    ]
