# Generated by Django 5.1.3 on 2024-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0007_remove_message_is_read_messagereadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereadstatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
