# Generated by Django 5.1.3 on 2024-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0009_alter_message_options_rename_message_message_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
