# Generated by Django 5.1.3 on 2024-12-01 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0013_alter_message_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='messagestatus',
            constraint=models.UniqueConstraint(fields=('message', 'profile'), name='unique_message_status'),
        ),
    ]
