# Generated by Django 5.1.3 on 2024-12-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_messages', '0014_messagestatus_unique_message_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagestatus',
            name='unique_message_status',
        ),
    ]
