name: Deploy Django to Azure

on:
  push:
    branches:
      - main  # Adjust to your default branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set working directory to the Django project
      working-directory: My-demo-projects/agro_marketplace
      run: echo "Working directory set to agro_marketplace"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Match your project's Python version

    - name: Install dependencies
      working-directory: my-demo-project/agro_marketplace  # Ensure it runs from your project folder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      working-directory: my-demo-project/agro_marketplace
      run: python manage.py test

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'agro_marketplace'
        slot-name: 'production'   
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
